SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF NOT EXISTS ( SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'UserPreferences'
AND COLUMN_NAME = 'EnterIsTab' )
BEGIN
	ALTER TABLE UserPreferences
	ADD EnterIsTab [dbo].[FlagNyType] NULL
END