IF NOT EXISTS ( SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ABProjects'
AND COLUMN_NAME = 'UrlVariables' )
BEGIN
       ALTER TABLE ABProjects
       ADD UrlVariables [dbo].[JSONStringType] NULL
END
