IF EXISTS ( SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'tmp_UserNotes'
AND COLUMN_NAME = 'NoteContent' )
ALTER TABLE tmp_UserNotes ALTER COLUMN NoteContent VeryLongListType NOT NULL
GO
IF EXISTS ( SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'SpecificNotes'
AND COLUMN_NAME = 'NoteContent' )
ALTER TABLE SpecificNotes ALTER COLUMN NoteContent VeryLongListType NOT NULL
GO
IF EXISTS ( SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'SystemNotes'
AND COLUMN_NAME = 'NoteContent' )
ALTER TABLE SystemNotes ALTER COLUMN NoteContent VeryLongListType NOT NULL
GO
IF EXISTS ( SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'NotesContentShadow'
AND COLUMN_NAME = 'NoteContent' )
ALTER TABLE NotesContentShadow ALTER COLUMN NoteContent VeryLongListType NOT NULL
GO
IF EXISTS ( SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'tmp_SpecificNotes'
AND COLUMN_NAME = 'NoteContent' )
ALTER TABLE tmp_SpecificNotes ALTER COLUMN NoteContent VeryLongListType NOT NULL
GO
IF EXISTS ( SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'tmp_SystemNotes'
AND COLUMN_NAME = 'NoteContent' )
ALTER TABLE tmp_SystemNotes ALTER COLUMN NoteContent VeryLongListType NOT NULL
GO
IF EXISTS ( SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'UserNotes'
AND COLUMN_NAME = 'NoteContent' )
ALTER TABLE UserNotes ALTER COLUMN NoteContent VeryLongListType NOT NULL
GO
