-- Translation tools: CountryPack Info Script
-- File generated by ndies on Friday, November 6, 2020; Version Mongoose.0011

SET NOCOUNT ON 
 
IF EXISTS (SELECT 1 FROM CountryPack WHERE [Option] = N'T' And [Name] = N'ja-JP') 
BEGIN 
    UPDATE [CountryPack] SET [Version] = N'Mongoose.0011'  
    WHERE [Option] = N'T' And [Name] = N'ja-JP' 
END 
ELSE 
BEGIN 
    INSERT INTO [CountryPack] ([Option], [Name], [Description], [Version]) 
    VALUES (N'T', N'ja-JP', N'Japanese (Japan)', N'Mongoose.0011')  
END 
GO
