-- Translation tools: CountryPack Info Script
-- File generated by ndies on Friday, April 10, 2020; Version 2020.5.0.3.0000

SET NOCOUNT ON 
 
IF EXISTS (SELECT 1 FROM CountryPack WHERE [Option] = N'T' And [Name] = N'bg-BG') 
BEGIN 
    UPDATE [CountryPack] SET [Version] = N'2020.5.0.3.0000'  
    WHERE [Option] = N'T' And [Name] = N'bg-BG' 
END 
ELSE 
BEGIN 
    INSERT INTO [CountryPack] ([Option], [Name], [Description], [Version]) 
    VALUES (N'T', N'bg-BG', N'Bulgarian (Bulgaria)', N'2020.5.0.3.0000')  
END 
GO
