-- Translation tools: CountryPack Info Script
-- File generated by ndies on Friday, November 6, 2020; Version Mongoose.0010

SET NOCOUNT ON 
 
IF EXISTS (SELECT 1 FROM CountryPack WHERE [Option] = N'T' And [Name] = N'zh-CN') 
BEGIN 
    UPDATE [CountryPack] SET [Version] = N'Mongoose.0010'  
    WHERE [Option] = N'T' And [Name] = N'zh-CN' 
END 
ELSE 
BEGIN 
    INSERT INTO [CountryPack] ([Option], [Name], [Description], [Version]) 
    VALUES (N'T', N'zh-CN', N'Chinese (People''s Republic of China)', N'Mongoose.0010')  
END 
GO
