-- Translation tools: CountryPack Info Script
-- File generated by ndies on Friday, November 6, 2020; Version Mongoose.0010

SET NOCOUNT ON 
 
IF EXISTS (SELECT 1 FROM CountryPack WHERE [Option] = N'T' And [Name] = N'de-DE') 
BEGIN 
    UPDATE [CountryPack] SET [Version] = N'Mongoose.0010'  
    WHERE [Option] = N'T' And [Name] = N'de-DE' 
END 
ELSE 
BEGIN 
    INSERT INTO [CountryPack] ([Option], [Name], [Description], [Version]) 
    VALUES (N'T', N'de-DE', N'German (Germany)', N'Mongoose.0010')  
END 
GO
