-- Translation tools: CountryPack Info Script
-- File generated by ndies on Friday, May 29, 2020; Version 2020.7.0.0.

SET NOCOUNT ON 
 
IF EXISTS (SELECT 1 FROM CountryPack WHERE [Option] = N'T' And [Name] = N'ro-RO') 
BEGIN 
    UPDATE [CountryPack] SET [Version] = N'2020.7.0.0.'  
    WHERE [Option] = N'T' And [Name] = N'ro-RO' 
END 
ELSE 
BEGIN 
    INSERT INTO [CountryPack] ([Option], [Name], [Description], [Version]) 
    VALUES (N'T', N'ro-RO', N'Romanian (Romania)', N'2020.7.0.0.')  
END 
GO
