-- Translation tools: CountryPack Info Script
-- File generated by ndies on Wednesday, March 20, 2019; Version 2019.03.0000

SET NOCOUNT ON 
 
IF EXISTS (SELECT 1 FROM CountryPack WHERE [Option] = N'T' And [Name] = N'sl-SI') 
BEGIN 
    UPDATE [CountryPack] SET [Version] = N'2019.03.0000'  
    WHERE [Option] = N'T' And [Name] = N'sl-SI' 
END 
ELSE 
BEGIN 
    INSERT INTO [CountryPack] ([Option], [Name], [Description], [Version]) 
    VALUES (N'T', N'sl-SI', N'Slovenian (Slovenia)', N'2019.03.0000')  
END 
GO
