-- Translation tools: CountryPack Info Script
-- File generated by ndies on Friday, May 29, 2020; Version CSIB10.0.0000

SET NOCOUNT ON 
 
IF EXISTS (SELECT 1 FROM CountryPack WHERE [Option] = N'T' And [Name] = N'ar-SA') 
BEGIN 
    UPDATE [CountryPack] SET [Version] = N'CSIB10.0.0000'  
    WHERE [Option] = N'T' And [Name] = N'ar-SA' 
END 
ELSE 
BEGIN 
    INSERT INTO [CountryPack] ([Option], [Name], [Description], [Version]) 
    VALUES (N'T', N'ar-SA', N'Arabic (Saudi Arabia)', N'CSIB10.0.0000')  
END 
GO
