SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[ValidateNextKeyAddKeysSp]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
drop procedure [dbo].[ValidateNextKeyAddKeysSp]
GO

/* $Header: /Tools/SQLScripts/Upgrade/PreUpgradeScripts/9.03.00_ValidateNextKeyAddKeysSp.sp 1     11/21/16 8:55a Djohnson $ */

/*
***************************************************************
*                                                             *
*                           NOTICE                            *
*                                                             *
*   THIS SOFTWARE IS THE PROPERTY OF AND CONTAINS             *
*   CONFIDENTIAL INFORMATION OF INFOR AND/OR ITS AFFILIATES   *
*   OR SUBSIDIARIES AND SHALL NOT BE DISCLOSED WITHOUT PRIOR  *
*   WRITTEN PERMISSION. LICENSED CUSTOMERS MAY COPY AND       *
*   ADAPT THIS SOFTWARE FOR THEIR OWN USE IN ACCORDANCE WITH  *
*   THE TERMS OF THEIR SOFTWARE LICENSE AGREEMENT.            *
*   ALL OTHER RIGHTS RESERVED.                                *
*                                                             *
*   (c) COPYRIGHT 2010 INFOR.  ALL RIGHTS RESERVED.           *
*   THE WORD AND DESIGN MARKS SET FORTH HEREIN ARE            *
*   TRADEMARKS AND/OR REGISTERED TRADEMARKS OF INFOR          *
*   AND/OR ITS AFFILIATES AND SUBSIDIARIES. ALL RIGHTS        *
*   RESERVED.  ALL OTHER TRADEMARKS LISTED HEREIN ARE         *
*   THE PROPERTY OF THEIR RESPECTIVE OWNERS.                  *
*                                                             *
***************************************************************
*/

/* $Archive: /Tools/SQLScripts/Upgrade/PreUpgradeScripts/9.03.00_ValidateNextKeyAddKeysSp.sp $
 *
 * CoreDev 1 218600 Djohnson Fri Nov 18 15:24:56 2016
 * Redesign form to maintain current function without risk of SQL injection.
 * Issue #218600
 *
 * $NoKeywords: $
 */
--  Validate that the values in the comma separated column list are valid columns on the table
-- specified.
CREATE PROCEDURE dbo.ValidateNextKeyAddKeysSp (
  @TableName  SYSNAME
, @ColumnList VeryLongListType
, @Infobar    InfobarType   OUTPUT
) AS

   -- Check for existence of Generic External Touch Point routine (this section was generated by SpETPCodeSp and inserted by CallETPs.exe):
   IF OBJECT_ID(N'dbo.EXTGEN_ValidateNextKeyAddKeysSp') IS NOT NULL
   BEGIN
      DECLARE @EXTGEN_SpName sysname
      SET @EXTGEN_SpName = N'dbo.EXTGEN_ValidateNextKeyAddKeysSp'
      -- Invoke the ETP routine, passing in (and out) this routine's parameters:
      DECLARE @EXTGEN_Severity int
      EXEC @EXTGEN_Severity = @EXTGEN_SpName
         @TableName
         , @ColumnList
         , @Infobar OUTPUT

      -- ETP routine can RETURN 1 to signal that the remainder of this standard routine should now proceed:
      IF @EXTGEN_Severity <> 1
         RETURN @EXTGEN_Severity
   END
   -- End of Generic External Touch Point code.

DECLARE
  @Severity  INT
, @BadColumn SYSNAME

SET @Severity = 0

IF @ColumnList IS NULL
   RETURN 0

SELECT TOP 1 @BadColumn = Element
FROM dbo.SplitString(N',', REPLACE(@ColumnList, N' ', N'')) ss
LEFT OUTER JOIN INFORMATION_SCHEMA.COLUMNS cc ON
  cc.COLUMN_NAME = ss.Element
AND cc.TABLE_NAME = @TableName
WHERE cc.COLUMN_NAME IS NULL

IF @BadColumn IS NOT NULL
BEGIN
   EXEC @Severity = MsgAppSp @Infobar OUTPUT
   , 'E=Invalid22'
   , '@AppColumn.NextkeyAddlKeys'
   , '@:ObjectType:1'
   , @TableName
   , '@AppColumn.ColumnName'
   , @BadColumn
END

RETURN @Severity

GO
