SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[MakeUpdateWhenSp]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
drop procedure [dbo].[MakeUpdateWhenSp]
GO


/* $Header: ApplicationDB\Stored Procedures\MakeUpdateWhenSp.sp 10.1.0.1 03/30/2018 14:27:36 */

/*
***************************************************************
*                                                             *
*                           NOTICE                            *
*                                                             *
*   THIS SOFTWARE IS THE PROPERTY OF AND CONTAINS             *
*   CONFIDENTIAL INFORMATION OF INFOR AND/OR ITS AFFILIATES   *
*   OR SUBSIDIARIES AND SHALL NOT BE DISCLOSED WITHOUT PRIOR  *
*   WRITTEN PERMISSION. LICENSED CUSTOMERS MAY COPY AND       *
*   ADAPT THIS SOFTWARE FOR THEIR OWN USE IN ACCORDANCE WITH  *
*   THE TERMS OF THEIR SOFTWARE LICENSE AGREEMENT.            *
*   ALL OTHER RIGHTS RESERVED.                                *
*                                                             *
*   (c) COPYRIGHT 2018 INFOR.  ALL RIGHTS RESERVED.           *
*   THE WORD AND DESIGN MARKS SET FORTH HEREIN ARE            *
*   TRADEMARKS AND/OR REGISTERED TRADEMARKS OF INFOR          *
*   AND/OR ITS AFFILIATES AND SUBSIDIARIES. ALL RIGHTS        *
*   RESERVED.  ALL OTHER TRADEMARKS LISTED HEREIN ARE         *
*   THE PROPERTY OF THEIR RESPECTIVE OWNERS.                  *
*                                                             *
***************************************************************
*/

/* $Archive: /Tools/SQLScripts/ApplicationDB/Stored Procedures/MakeUpdateWhenSp.sp $
 *
 * CoreDev 2 248405 DJohnson Thu Oct 04
 * Add dbo. schema to path where missing.
 *
 * CoreDev 1 218600 Djohnson Fri Nov 18 15:23:21 2016
 * Redesign form to maintain current function without risk of SQL injection.
 * Issue #218600
 *
 * $NoKeywords: $
 */
CREATE PROCEDURE dbo.MakeUpdateWhenSp (
  @UpdateList VeryLongListType
, @UpdateCode VeryLongListType OUTPUT
, @Infobar    InfobarType      OUTPUT
) AS

   -- Check for existence of Generic External Touch Point routine (this section was generated by SpETPCodeSp and inserted by CallETPs.exe):
   IF OBJECT_ID(N'dbo.EXTGEN_MakeUpdateWhenSp') IS NOT NULL
   BEGIN
      DECLARE @EXTGEN_SpName sysname
      SET @EXTGEN_SpName = N'dbo.EXTGEN_MakeUpdateWhenSp'
      -- Invoke the ETP routine, passing in (and out) this routine's parameters:
      DECLARE @EXTGEN_Severity int
      EXEC @EXTGEN_Severity = @EXTGEN_SpName
         @UpdateList
         , @UpdateCode OUTPUT
         , @Infobar OUTPUT
 
      -- ETP routine can RETURN 1 to signal that the remainder of this standard routine should now proceed:
      IF @EXTGEN_Severity <> 1
         RETURN @EXTGEN_Severity
   END
   -- End of Generic External Touch Point code.
 
DECLARE
  @Severity INT
, @Value    VeryLongListType

SET @Severity = 0
SET @UpdateCode = N''

IF @UpdateList IS NULL
   RETURN 0

IF CHARINDEX(N'''', @UpdateList) > 0
BEGIN
   EXEC @Severity = dbo.MsgAppSp @Infobar OUTPUT
   , 'E=InvalidUpdateWhen'
   , @UpdateList
   RETURN @Severity
END

DECLARE
  @ValueList TABLE ( 
   ValueColumn VeryLongListType
   , RowNumber INT IDENTITY )

INSERT INTO @ValueList ( ValueColumn )
SELECT dbo.DoubleQuote(Element)
FROM dbo.SplitString (',', @UpdateList)
WHERE ISNULL(Element, N'') <> N''
IF @@ROWCOUNT = 0
   RETURN 0


SELECT
  @UpdateCode = @UpdateCode + CASE WHEN RowNumber = 1 THEN '' ELSE ' AND ' END +
N'dbo.VariableIsDefined(''' + ValueColumn + ''') = 0'
FROM @ValueList

RETURN @Severity

GO
