SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF OBJECT_ID('dbo.CreateViewsOverMultiSiteTabsSp') IS NOT NULL
    DROP PROCEDURE dbo.CreateViewsOverMultiSiteTabsSp
GO
/* $Header: ApplicationDB\Stored Procedures\CreateViewsOverMultiSiteTabsSp.sp 10.1.0.1 03/30/2018 14:27:36 */
/*
***************************************************************
*                                                             *
*                           NOTICE                            *
*                                                             *
*   THIS SOFTWARE IS THE PROPERTY OF AND CONTAINS             *
*   CONFIDENTIAL INFORMATION OF INFOR AND/OR ITS AFFILIATES   *
*   OR SUBSIDIARIES AND SHALL NOT BE DISCLOSED WITHOUT PRIOR  *
*   WRITTEN PERMISSION. LICENSED CUSTOMERS MAY COPY AND       *
*   ADAPT THIS SOFTWARE FOR THEIR OWN USE IN ACCORDANCE WITH  *
*   THE TERMS OF THEIR SOFTWARE LICENSE AGREEMENT.            *
*   ALL OTHER RIGHTS RESERVED.                                *
*                                                             *
*   (c) COPYRIGHT 2018 INFOR.  ALL RIGHTS RESERVED.           *
*   THE WORD AND DESIGN MARKS SET FORTH HEREIN ARE            *
*   TRADEMARKS AND/OR REGISTERED TRADEMARKS OF INFOR          *
*   AND/OR ITS AFFILIATES AND SUBSIDIARIES. ALL RIGHTS        *
*   RESERVED.  ALL OTHER TRADEMARKS LISTED HEREIN ARE         *
*   THE PROPERTY OF THEIR RESPECTIVE OWNERS.                  *
*                                                             *
***************************************************************
*/
/* $Archive: /Tools/SQLScripts/ApplicationDB/Stored Procedures/CreateViewsOverMultiSiteTabsSp.sp $
 * CoreDev 7 MGD-1292 nelaba Mon May 03 2021
 * Fix issue on this SP not returning the Infobar as output when RegenerateSiteViewSp is executed.
 *
 * CoreDev 6 248405 DJohnson Thu Oct 04
 * Add dbo. schema to path where missing.
 *
 * Core90310 5 227711 ihow Mon Jun 05 17:38:57 2017
 * Create Application Database failed in Configuration wizard when SQL collation is not "SQL_Latin1_General_CPI_CI_AS  "
 * 227711 - Additional checkin to remove duplicate comments.
 *
 * Core90310 4 227711 ihow Fri Apr 28 14:26:52 2017
 * Create Application Database failed in Configuration wizard when SQL collation is not "SQL_Latin1_General_CPI_CI_AS  "
 * 227711 - Specify TableName column to compare in SQL_Latin1_General_CP1_CI_AS collation in the WHERE clause.
 *
 * CoreDev 3 224509 Pgross Thu Feb 16 09:45:40 2017
 * delete triggers not working in multisite not in single database for _all table records
 * verify existence in objects instead of tables
 *
 * CoreDev 2 210076 Djohnson Tue Apr 19 13:03:08 2016
 * Incorrect syntax near the keyword 'FROM'.
 * Issue #210076 - exclude tables that do not exist.
 *
 * CoreDev 1 RS5077 Djohnson Fri Aug 01 16:36:19 2014
 * Shortened names (30 or less) for existing procedures.
 *
 * CoreDev 1 RS9110 dartiaga 02/11/2021
 * RS9110 - Add code to update table hash on manual regen
 *
 * $NoKeywords: $
 */
/* $Archive: /Tools/SQLScripts/Upgrade/PreUpgradeScripts/CreateViewsOverMultiSiteTabsSp.sp $
 *
 * CoreDev 5 RS5905 Lpeng Wed Feb 06 05:07:12 2013
 * RS5905
 *
 * $NoKeywords: $
 */

CREATE PROCEDURE [dbo].[CreateViewsOverMultiSiteTabsSp]
   @StartingTable TableNameType=NULL,     -- _mst table
   @EndingTable   TableNameType=NULL,     -- _mst table
   @Infobar       InfobarType OUTPUT
AS

-- Check for existence of Generic External Touch Point routine (this section was generated by SpETPCodeSp and inserted by CallETPs.exe):
IF OBJECT_ID(N'dbo.EXTGEN_CreateViewsOverMultiSiteTabsSp') IS NOT NULL
BEGIN
   DECLARE @EXTGEN_SpName sysname
   SET @EXTGEN_SpName = N'dbo.EXTGEN_CreateViewsOverMultiSiteTabsSp'
   -- Invoke the ETP routine, passing in (and out) this routine's parameters:
   DECLARE @EXTGEN_Severity int 
   EXEC @EXTGEN_Severity = @EXTGEN_SpName
      @StartingTable
      , @EndingTable
      , @Infobar OUTPUT

-- ETP routine can RETURN 1 to signal that the remainder of this standard routine should now proceed: 
 IF @EXTGEN_Severity <> 1 
  RETURN @EXTGEN_Severity 
 END 
 -- End of Generic External Touch Point code. 

DECLARE
   @Severity INT = 0,
   @MultiSiteTableName ObjectNameType,
   @IncludeSiteRefFilter ListYesNoType = 0,
   @LowChar HighLowCharType,
   @HighChar   HighLowCharType,
   @TablesProcessed INT

SET @Infobar = NULL
SET @LowChar      = dbo.LowCharacter()
SET @HighChar     = dbo.HighCharacter()
SET @StartingTable = ISNULL(@StartingTable, @LowChar)
SET @EndingTable = ISNULL(@EndingTable, @HighChar)
SET @TablesProcessed = 0;


-- Create Views over Multi-Site Tables

----Loop through Multi-Site Tables 
----And call routine to create View over Multi-Site Table

----If NULL value is passed to @StartingTable and @EndingTable, the NULL value will be replaced by
----values returned from LowCharacter() and HighCharacter().  The Collate statement in WHERE clause
----coverts TableName to SQL_Latin1_General_CP1_CI_AS collation regardless the default language of  
----the Windows Server and SQL Server is set up.  In some Asian language, HighCharacter() function will
----not sort as expected in the "between" statement and it may not return correct the TableNames.
----See Issue 227711.
DECLARE MultiSiteTableCrs CURSOR LOCAL STATIC FOR
   SELECT TableName
   FROM AppTable 
   INNER JOIN sys.objects st ON
     st.name = AppTable.TableName
   WHERE TableName Collate SQL_Latin1_General_CP1_CI_AS between @StartingTable and @EndingTable
      AND AppViewName is not NULL
   ORDER BY TableName

OPEN MultiSiteTableCrs
FETCH NEXT FROM MultiSiteTableCrs INTO @MultiSiteTableName
WHILE @@FETCH_STATUS = 0
BEGIN

   SET @IncludeSiteRefFilter = CASE
                                  WHEN @MultiSiteTableName LIKE N'%[_]all' THEN
                                     0
                                  ELSE
                                     1
                               END

   EXECUTE @Severity = [dbo].[RegenerateSiteViewSp]
      @TableName = @MultiSiteTableName
    , @IncludeSiteRefFilter = @IncludeSiteRefFilter
    , @Infobar = @Infobar OUTPUT

   IF @Severity != 0
   BEGIN
      RETURN @Severity
   END
   ELSE
   BEGIN
      /* RS9110 - Selectively regenerate views and triggers */
	  DECLARE @NewHash	HashStateType
	  SET @NewHash = dbo.GetTableStateHash(@MultiSiteTableName)
	  EXEC InsertUpdateTableStateSp @TableName = @MultiSiteTableName, @ViewState = @NewHash		-- update record with new hash

      SET @TablesProcessed = @TablesProcessed + 1
   END
      
FETCH NEXT FROM MultiSiteTableCrs INTO @MultiSiteTableName
END

EXEC
   dbo.MsgAppSp @Infobar OUTPUT,
   N'I=#Processed',
   @TablesProcessed,
   N'@!sysobjects:U'

CLOSE MultiSiteTableCrs
DEALLOCATE MultiSiteTableCrs

RETURN @Severity

GO

