SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[GetVariableSp]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
drop procedure [dbo].[GetVariableSp]
GO


/* $Header: ApplicationDB\Stored Procedures\GetVariableSp.sp 10.1.0.1 03/30/2018 14:27:36 */

/*

***************************************************************

*                                                             *

*                           NOTICE                            *

*                                                             *

*   THIS SOFTWARE IS THE PROPERTY OF AND CONTAINS             *

*   CONFIDENTIAL INFORMATION OF INFOR AND/OR ITS AFFILIATES   *

*   OR SUBSIDIARIES AND SHALL NOT BE DISCLOSED WITHOUT PRIOR  *

*   WRITTEN PERMISSION. LICENSED CUSTOMERS MAY COPY AND       *

*   ADAPT THIS SOFTWARE FOR THEIR OWN USE IN ACCORDANCE WITH  *

*   THE TERMS OF THEIR SOFTWARE LICENSE AGREEMENT.            *

*   ALL OTHER RIGHTS RESERVED.                                *

*                                                             *

*   (c) COPYRIGHT 2018 INFOR.  ALL RIGHTS RESERVED.           *

*   THE WORD AND DESIGN MARKS SET FORTH HEREIN ARE            *

*   TRADEMARKS AND/OR REGISTERED TRADEMARKS OF INFOR          *

*   AND/OR ITS AFFILIATES AND SUBSIDIARIES. ALL RIGHTS        *

*   RESERVED.  ALL OTHER TRADEMARKS LISTED HEREIN ARE         *

*   THE PROPERTY OF THEIR RESPECTIVE OWNERS.                  *

*                                                             *

***************************************************************

*/

/* $Archive: /Tools/SQLScripts/ApplicationDB/Stored Procedures/GetVariableSp.sp $
 *
 * CoreDev 9 248405 DJohnson Thu Oct 04
 * Add dbo. schema to path where missing.
 *
 * CoreDev 8 RS7846 Lobkrom Tue Apr 18 10:37:15 2017
 * RS7846 -- update length of VariableValue on DefineVariables
 *
 * CoreDev 7 rs4588 Dahn Mon Mar 08 08:26:52 2010
 * rs4588 copyright header changes.
 *
 * CoreDev 6 rs3953 Dahn Tue Aug 26 16:26:07 2008
 * changing copyright header (rs3953)
 *
 * CoreDev 5 rs3953 Vlitmano Mon Aug 18 16:07:42 2008
 * Changed a Copyright header information(RS3959)
 *
 * $NoKeywords: $
 */
CREATE PROCEDURE dbo.GetVariableSp(
  @VariableName  	SYSNAME
, @DefaultValue  	VeryLongListType
, @DeleteVariable       ListYesNoType
, @VariableValue 	VeryLongListType OUTPUT
, @Infobar              InfobarType OUTPUT )
AS

   -- Check for existence of Generic External Touch Point routine (this section was generated by SpETPCodeSp and inserted by CallETPs.exe):
   IF OBJECT_ID(N'dbo.EXTGEN_GetVariableSp') IS NOT NULL
   BEGIN
      DECLARE @EXTGEN_SpName sysname
      SET @EXTGEN_SpName = N'dbo.EXTGEN_GetVariableSp'
      -- Invoke the ETP routine, passing in (and out) this routine's parameters:
      DECLARE @EXTGEN_Severity int
      EXEC @EXTGEN_Severity = @EXTGEN_SpName
         @VariableName
         , @DefaultValue
         , @DeleteVariable
         , @VariableValue OUTPUT
         , @Infobar OUTPUT
 
      -- ETP routine can RETURN 1 to signal that the remainder of this standard routine should now proceed:
      IF @EXTGEN_Severity <> 1
         RETURN @EXTGEN_Severity
   END
   -- End of Generic External Touch Point code.
 
/*
 * PURPOSE:
 *   Core toolset procedure for retrieving session variables.
 */

DECLARE @Severity INT

SET @Severity = 0

IF dbo.VariableIsDefined(@VariableName) = 1
BEGIN
   SET @VariableValue = dbo.DefinedValue(@VariableName)
   IF @DeleteVariable <> 0
      EXEC @Severity = dbo.UndefineVariableSp @VariableName, @Infobar OUTPUT
END
ELSE
   SET @VariableValue = @DefaultValue

RETURN @Severity

GO
