SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
IF OBJECT_ID('dbo.UndefineVariableSp') IS NOT NULL
    DROP PROCEDURE dbo.UndefineVariableSp
GO

-- This routine undefines a global variable for the current session ID.

/* $Header: ApplicationDB\Stored Procedures\UndefineVariableSp.sp 10.1.0.1 03/30/2018 14:27:37 */

/*
***************************************************************
*                                                             *
*                           NOTICE                            *
*                                                             *
*   THIS SOFTWARE IS THE PROPERTY OF AND CONTAINS             *
*   CONFIDENTIAL INFORMATION OF INFOR AND/OR ITS AFFILIATES   *
*   OR SUBSIDIARIES AND SHALL NOT BE DISCLOSED WITHOUT PRIOR  *
*   WRITTEN PERMISSION. LICENSED CUSTOMERS MAY COPY AND       *
*   ADAPT THIS SOFTWARE FOR THEIR OWN USE IN ACCORDANCE WITH  *
*   THE TERMS OF THEIR SOFTWARE LICENSE AGREEMENT.            *
*   ALL OTHER RIGHTS RESERVED.                                *
*                                                             *
*   (c) COPYRIGHT 2018 INFOR.  ALL RIGHTS RESERVED.           *
*   THE WORD AND DESIGN MARKS SET FORTH HEREIN ARE            *
*   TRADEMARKS AND/OR REGISTERED TRADEMARKS OF INFOR          *
*   AND/OR ITS AFFILIATES AND SUBSIDIARIES. ALL RIGHTS        *
*   RESERVED.  ALL OTHER TRADEMARKS LISTED HEREIN ARE         *
*   THE PROPERTY OF THEIR RESPECTIVE OWNERS.                  *
*                                                             *
***************************************************************
*/

/* $Archive: /Tools/SQLScripts/ApplicationDB/Stored Procedures/UndefineVariableSp.sp $
 *
 * CoreDev 9 134530 Calagappan Tue Jan 04 10:46:00 2011
 * Invoice Distribution wrong when Debit/Credit memo is from  Price Adjustment Invoice and CO is "include tax in price"
 * Obtain and pass in session ID to UnDefineVariableBySessionIdSp
 *
 * CoreDev 8 rs4588 Dahn Mon Mar 08 08:30:09 2010
 * rs4588 copyright header changes.
 *
 * CoreDev 7 rs3953 Dahn Tue Aug 26 16:30:30 2008
 * changing copyright header (rs3953)
 *
 * CoreDev 6 rs3953 Vlitmano Mon Aug 18 16:10:41 2008
 * Changed a Copyright header information(RS3959)
 *
 * SL8.00 9 RS2968 nkaleel Thu Feb 08 03:18:51 2007
 * changing copyright information
 *
 * SL8.00 8 RS2968 prahaladarao.hs Wed Jul 12 02:55:05 2006
 * RS 2968, Name change CopyRight Update.
 *
 * SL7.05 7 91818 NThurn Fri Jan 06 18:34:32 2006
 * Inserted standard External Touch Point call.  (RS3177)
 *
 * $NoKeywords: $
 */
CREATE PROCEDURE dbo.UndefineVariableSp (
  @VariableName SYSNAME
, @Infobar      InfobarType OUTPUT
)
AS

   -- Check for existence of Generic External Touch Point routine (this section was generated by SpETPCodeSp and inserted by CallETPs.exe):
   IF OBJECT_ID(N'dbo.EXTGEN_UndefineVariableSp') IS NOT NULL
   BEGIN
      DECLARE @EXTGEN_SpName sysname
      SET @EXTGEN_SpName = N'dbo.EXTGEN_UndefineVariableSp'
      -- Invoke the ETP routine, passing in (and out) this routine's parameters:
      DECLARE @EXTGEN_Severity int
      EXEC @EXTGEN_Severity = @EXTGEN_SpName
         @VariableName
         , @Infobar OUTPUT
 
      -- ETP routine can RETURN 1 to signal that the remainder of this standard routine should now proceed:
      IF @EXTGEN_Severity <> 1
         RETURN @EXTGEN_Severity
   END
   -- End of Generic External Touch Point code.
 
DECLARE
  @Severity  INT
, @SessionID RowPointerType

SET @Severity  = 0
SET @SessionID = dbo.SessionIDSp()

EXEC @Severity = dbo.UndefineVariableBySessionIdSp
     @SessionID    = @SessionID
   , @VariableName = @VariableName
   , @Infobar      = @Infobar OUTPUT

RETURN @Severity
GO
