-- Translation tools: CountryPack Info Script
-- File generated by ndies on Friday, November 6, 2020; Version Mongoose.0008

SET NOCOUNT ON 
 
IF EXISTS (SELECT 1 FROM CountryPack WHERE [Option] = N'T' And [Name] = N'fr-FR') 
BEGIN 
    UPDATE [CountryPack] SET [Version] = N'Mongoose.0008'  
    WHERE [Option] = N'T' And [Name] = N'fr-FR' 
END 
ELSE 
BEGIN 
    INSERT INTO [CountryPack] ([Option], [Name], [Description], [Version]) 
    VALUES (N'T', N'fr-FR', N'French (France)', N'Mongoose.0008')  
END 
GO
